/**
 * Generate `src/i18n/messages.ts` (+ one `messages.<locale>.ts` per
 * non-source locale) from `locales/*.json`.
 *
 * Mirrors `scripts/build-privacy-page.ts`:
 *   - Validates input against `locales/schema.json`-equivalent rules
 *     (flat key→string, key regex `^[a-z][a-zA-Z0-9.]*$`).
 *   - Diffs every non-source locale against `en.json`. Missing-in-
 *     target = warn. Extra-in-target = fail. Missing-in-source = fail.
 *   - Emits deterministic TypeScript so `--check` mode (CI) can byte-
 *     compare on-disk generated files against a fresh render.
 *
 * Runs in `postinstall`, `predev`, `prebuild`, and `type-check`. The
 * generated files are gitignored next to `src/styles/tokens.css`.
 *
 * See `docs/I18N_PLAN.md`.
 */

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, basename } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const HERE = resolve(fileURLToPath(import.meta.url), '..')
const REPO_ROOT = resolve(HERE, '..')
const LOCALES_DIR = resolve(REPO_ROOT, 'locales')
const OUTPUT_DIR = resolve(REPO_ROOT, 'src/i18n')
const SOURCE_LOCALE = 'en'
const KEY_RE = /^[a-z][a-zA-Z0-9.]*$/

/** Native names for the language picker. Edit when adding a locale. */
const NATIVE_NAMES: Readonly<Record<string, string>> = {
  en: 'English',
  es: 'Español',
}

interface LocaleFile {
  readonly locale: string
  readonly path: string
  readonly messages: Readonly<Record<string, string>>
}

interface RenderResult {
  readonly path: string
  readonly contents: string
}

interface BuildOutput {
  readonly files: readonly RenderResult[]
  readonly warnings: readonly string[]
}

class LocaleBuildError extends Error {}

// ---- Pure functions (exported for testing) ─────────────────────────

/**
 * Validate one parsed locale object against the schema rules. Throws
 * `LocaleBuildError` on the first violation; the message names the
 * locale and the offending key.
 */
export function validateLocale(
  locale: string,
  parsed: unknown,
): asserts parsed is Record<string, string> {
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new LocaleBuildError(
      `[locales] ${locale}.json must be a JSON object, got ${
        Array.isArray(parsed) ? 'array' : typeof parsed
      }`,
    )
  }
  for (const [key, value] of Object.entries(parsed)) {
    if (!KEY_RE.test(key)) {
      throw new LocaleBuildError(
        `[locales] ${locale}.json: key "${key}" violates ${KEY_RE.source}`,
      )
    }
    if (typeof value !== 'string') {
      throw new LocaleBuildError(
        `[locales] ${locale}.json: value for "${key}" must be a string, got ${typeof value}`,
      )
    }
  }
}

/**
 * Diff a non-source locale against the source. Missing in target =
 * warning (translation pending). Extra in target = error (orphan
 * key). Missing in source via this locale = error (handled separately
 * by re-checking each locale against the union of all keys).
 */
export function diffAgainstSource(
  locale: string,
  source: Readonly<Record<string, string>>,
  target: Readonly<Record<string, string>>,
): { warnings: string[]; errors: string[] } {
  const warnings: string[] = []
  const errors: string[] = []
  const sourceKeys = new Set(Object.keys(source))
  const targetKeys = new Set(Object.keys(target))
  for (const key of sourceKeys) {
    if (!targetKeys.has(key)) {
      warnings.push(`[locales] ${locale}.json: missing translation for "${key}"`)
    }
  }
  for (const key of targetKeys) {
    if (!sourceKeys.has(key)) {
      errors.push(
        `[locales] ${locale}.json: orphan key "${key}" not in en.json — add it to en.json first`,
      )
    }
  }
  return { warnings, errors }
}

/** Render the per-locale `messages.<locale>.ts` file. */
export function renderLocaleModule(
  locale: string,
  messages: Readonly<Record<string, string>>,
): string {
  const sortedEntries = Object.keys(messages)
    .sort()
    .map((k) => [k, messages[k]] as const)
  const lines = [
    '// AUTO-GENERATED by scripts/generate-locales.ts. Do not edit directly.',
    `// Source: locales/${locale}.json`,
    '',
    'const messages = {',
    ...sortedEntries.map(
      ([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`,
    ),
    '} as const',
    '',
    'export default messages',
    '',
  ]
  return lines.join('\n')
}

/**
 * Render the entry `messages.ts` — re-exports English statically,
 * provides lazy loaders for all non-source locales, and emits the
 * `MessageKey` type derived from English.
 *
 * When `en.json` is empty, `MessageKey` widens to `string` so callers
 * (including tests) aren't blocked. Once Wave 1 starts populating
 * keys, the type narrows automatically.
 */
export function renderEntryModule(
  locales: readonly string[],
  source: Readonly<Record<string, string>>,
): string {
  const sortedLocales = [...locales].sort()
  const sortedEntries = Object.keys(source)
    .sort()
    .map((k) => [k, source[k]] as const)

  const localeUnion = sortedLocales.map((l) => JSON.stringify(l)).join(' | ')
  const localeArrayLiteral = sortedLocales
    .map((l) => `  ${JSON.stringify(l)},`)
    .join('\n')
  const nativeNamesEntries = sortedLocales
    .map((l) => `  ${JSON.stringify(l)}: ${JSON.stringify(NATIVE_NAMES[l] ?? l)},`)
    .join('\n')
  const loaderEntries = sortedLocales
    .map((l) =>
      l === SOURCE_LOCALE
        ? `  ${JSON.stringify(l)}: async () => enMessages,`
        : `  ${JSON.stringify(l)}: () => import('./messages.${l}').then((m) => m.default),`,
    )
    .join('\n')

  const lines = [
    '// AUTO-GENERATED by scripts/generate-locales.ts. Do not edit directly.',
    '',
    `export type Locale = ${localeUnion || "''"}`,
    '',
    `export const SOURCE_LOCALE: Locale = ${JSON.stringify(SOURCE_LOCALE)}`,
    '',
    'export const SUPPORTED_LOCALES: readonly Locale[] = [',
    localeArrayLiteral,
    '] as const',
    '',
    'export const NATIVE_NAMES: Readonly<Record<Locale, string>> = {',
    nativeNamesEntries,
    '}',
    '',
    '/** English source bundle — always available synchronously. */',
    'const enLiteral = {',
    ...sortedEntries.map(
      ([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`,
    ),
    '} as const',
    '',
    'export const enMessages: Readonly<Record<string, string>> = enLiteral',
    '',
    '/**',
    ' * Literal-key union when entries exist; widens to `string` while',
    ' * `en.json` is empty so callers aren\'t blocked.',
    ' */',
    'export type MessageKey = keyof typeof enLiteral extends never',
    '  ? string',
    '  : keyof typeof enLiteral',
    '',
    '/** Lazy loaders, one per locale. English resolves synchronously. */',
    'export const localeLoaders: Readonly<',
    '  Record<Locale, () => Promise<Readonly<Record<string, string>>>>',
    '> = {',
    loaderEntries,
    '}',
    '',
  ]
  return lines.join('\n')
}

/** Read every `locales/*.json` (excluding the schema). */
export function readLocales(localesDir: string = LOCALES_DIR): LocaleFile[] {
  const files = readdirSync(localesDir)
    .filter((name) => name.endsWith('.json') && name !== 'schema.json')
    .sort()
  return files.map((name) => {
    const path = resolve(localesDir, name)
    const locale = basename(name, '.json')
    const raw = readFileSync(path, 'utf-8')
    let parsed: unknown
    try {
      parsed = JSON.parse(raw)
    } catch (err) {
      throw new LocaleBuildError(
        `[locales] ${name}: invalid JSON — ${(err as Error).message}`,
      )
    }
    validateLocale(locale, parsed)
    return { locale, path, messages: parsed }
  })
}

/**
 * Validate + render. Returns the list of files to write and any
 * warnings. Throws `LocaleBuildError` on any hard failure.
 */
export function build(localesDir: string = LOCALES_DIR): BuildOutput {
  const locales = readLocales(localesDir)
  if (locales.length === 0) {
    throw new LocaleBuildError(
      `[locales] no locale files found in ${localesDir}`,
    )
  }
  const source = locales.find((l) => l.locale === SOURCE_LOCALE)
  if (!source) {
    throw new LocaleBuildError(
      `[locales] source locale "${SOURCE_LOCALE}.json" missing`,
    )
  }

  const warnings: string[] = []
  const errors: string[] = []
  for (const loc of locales) {
    if (loc.locale === SOURCE_LOCALE) continue
    const diff = diffAgainstSource(loc.locale, source.messages, loc.messages)
    warnings.push(...diff.warnings)
    errors.push(...diff.errors)
  }
  if (errors.length > 0) {
    throw new LocaleBuildError(errors.join('\n'))
  }

  const files: RenderResult[] = []
  files.push({
    path: resolve(OUTPUT_DIR, 'messages.ts'),
    contents: renderEntryModule(
      locales.map((l) => l.locale),
      source.messages,
    ),
  })
  for (const loc of locales) {
    if (loc.locale === SOURCE_LOCALE) continue
    files.push({
      path: resolve(OUTPUT_DIR, `messages.${loc.locale}.ts`),
      contents: renderLocaleModule(loc.locale, loc.messages),
    })
  }
  return { files, warnings }
}

// ---- CLI entry point ────────────────────────────────────────────────

function run(): void {
  const checkMode = process.argv.includes('--check')
  let output: BuildOutput
  try {
    output = build()
  } catch (err) {
    if (err instanceof LocaleBuildError) {
      console.error(err.message)
      process.exit(1)
    }
    throw err
  }

  for (const w of output.warnings) {
    // eslint-disable-next-line no-console
    console.warn(w)
  }

  if (checkMode) {
    let stale = false
    for (const file of output.files) {
      let current = ''
      try {
        current = readFileSync(file.path, 'utf-8')
      } catch {
        // missing file — definitely stale
      }
      if (current !== file.contents) {
        console.error(
          `✗ ${file.path} is stale.\n  Run \`npm run locales\` and commit the regenerated file.`,
        )
        stale = true
      }
    }
    if (stale) process.exit(1)
    // eslint-disable-next-line no-console
    console.log(`✓ ${output.files.length} locale module(s) up to date`)
    return
  }

  mkdirSync(OUTPUT_DIR, { recursive: true })
  for (const file of output.files) {
    writeFileSync(file.path, file.contents, 'utf-8')
    // eslint-disable-next-line no-console
    console.log(`✓ Generated ${file.path} (${file.contents.length} bytes)`)
  }
}

// CLI-mode detection — `pathToFileURL` normalizes `process.argv[1]`
// across platforms (Windows backslashes + drive letter, POSIX slashes)
// so the comparison matches `import.meta.url`. The naive
// `file://${process.argv[1]}` template silently misses on Windows
// runners, leaving `run()` un-invoked and the codegen producing no
// output — which then fails the downstream vite build with an
// unresolved-import error pointing at `./messages`.
if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  run()
}

export { LocaleBuildError, NATIVE_NAMES, SOURCE_LOCALE }
